/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia.vista;

import ar.com.lujan.asistencia.database.AsistenciaClaseDAO;
import ar.com.lujan.asistencia.database.CarreraMateriaDAO;
import ar.com.lujan.asistencia.database.CursoDAO;
import ar.com.lujan.asistencia.database.MateriaDAO;
import ar.com.lujan.asistencia.database.CarreraDAO;
import ar.com.lujan.asistencia.database.ProfesorDAO;
import ar.com.lujan.asistencia.modelo.Alumno;
import ar.com.lujan.asistencia.modelo.Carrera;
import ar.com.lujan.asistencia.modelo.CarreraMateria;
import ar.com.lujan.asistencia.modelo.CarreraMateriaTableModel;
import ar.com.lujan.asistencia.modelo.Curso;
import ar.com.lujan.asistencia.modelo.CursoTableModel;
import ar.com.lujan.asistencia.modelo.Materia;
import ar.com.lujan.asistencia.modelo.Profesor;
import ar.com.lujan.asistencia.vista.AgregarCursoUI;
import java.sql.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class ABMCurso extends javax.swing.JDialog {
    

    public ABMCurso(java.awt.Frame parent, boolean modal, boolean asistencia) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.cargarGrilla();
        
        if(asistencia){
            jbAgregar.setEnabled(false);
            jbAgregar.setVisible(false);
            jbBorrar.setEnabled(false);
            jbBorrar.setVisible(false);
            jbEditar.setEnabled(false);
            jbEditar.setVisible(false);
            jbGenerarAsistencia.setVisible(false);
            jbGenerarAsistencia.setEnabled(false);
            jbAsistencia.setEnabled(true);
            jbAsistencia.setVisible(true);
        }else{
            jbAgregar.setEnabled(true);
            jbAgregar.setVisible(true);
            jbBorrar.setEnabled(false);
            jbBorrar.setVisible(true);
            jbEditar.setEnabled(false);
            jbEditar.setVisible(true);
            jbGenerarAsistencia.setVisible(true);
            jbGenerarAsistencia.setEnabled(false);
            jbAsistencia.setEnabled(false);
            jbAsistencia.setVisible(false);
        }
            
    }

    private void cargarGrilla() {
        jtCursos.setModel(new CursoTableModel((new CursoDAO()).getCursos()));
        
        //inhabilita los botones en caso que no se este seleccionando ningun objeto de la grilla.
        jbEditar.setEnabled(false);
        jbBorrar.setEnabled(false);               

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void cargarGrillaByFilters() {
        try {
            if (cmbCarrera.getSelectedIndex() == 0 && cmbMateria.getSelectedIndex() == 0) //  jtCursos.setModel(new CarreraMateriaTableModel((new CarreraMateriaDAO()).getCarreraMateria())
            {
                jtCursos.setModel(new CursoTableModel((new CursoDAO()).getCursos())
                );
            }
            if (cmbCarrera.getSelectedIndex() != 0 && cmbMateria.getSelectedIndex() == 0 && cmbProfesor.getSelectedIndex() == 0) {
                Carrera carrera = (Carrera) cmbCarrera.getSelectedItem();
                jtCursos.setModel(new CursoTableModel((new CursoDAO()).getCursosByCarrera(carrera)));
            }
            if (cmbCarrera.getSelectedIndex() == 0 && cmbMateria.getSelectedIndex() != 0 && cmbProfesor.getSelectedIndex() == 0) {
                Materia materia = (Materia) cmbMateria.getSelectedItem();
                jtCursos.setModel(new CursoTableModel((new CursoDAO()).getCursosByMateria(materia)));
            }
            if(cmbCarrera.getSelectedIndex() == 0 && cmbMateria.getSelectedIndex() == 0 && cmbProfesor.getSelectedIndex() != 0){
                Profesor profesor = (Profesor) cmbProfesor.getSelectedItem();
                jtCursos.setModel(new CursoTableModel((new CursoDAO()).getCursosByProfesor(profesor)));
            }
            if (cmbCarrera.getSelectedIndex() != 0 && cmbMateria.getSelectedIndex() != 0) {
                Carrera carrera = (Carrera) cmbCarrera.getSelectedItem();
                Materia materia = (Materia) cmbMateria.getSelectedItem();
                jtCursos.setModel(new CursoTableModel((new CursoDAO()).getCursosByCarreraMateria(carrera, materia)));
            }
        } catch (Exception e) {
            // llamaria al mensaje de error e.
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jtCursos = new javax.swing.JTable();
        jbBorrar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        cmbCarrera = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbMateria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbCuatrimestre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbProfesor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jbAsistencia = new javax.swing.JButton();
        jbGenerarAsistencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM - Curso");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jtCursos.setModel(new CursoTableModel((new CursoDAO()).getCursos()));
        jtCursos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtCursos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCursosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtCursos);

        jbBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        cmbCarrera.setModel(new DefaultComboBoxModel( (new CarreraDAO()).getCarreras().toArray()));
        cmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarreraActionPerformed(evt);
            }
        });

        jLabel1.setText("Carrera");

        cmbMateria.setModel(new DefaultComboBoxModel( (new MateriaDAO()).getMaterias().toArray()));
        cmbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMateriaActionPerformed(evt);
            }
        });

        jLabel2.setText("Materia");

        cmbCuatrimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 - Todos los Cuatrimestres", "1 - Primer cuatrimestre", "2 - Segundo cuatrimestre" }));

        jLabel4.setText("Cuatrimestre");

        cmbProfesor.setModel(new DefaultComboBoxModel((new ProfesorDAO()).getProfesor().toArray()));
        cmbProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProfesorActionPerformed(evt);
            }
        });

        jLabel6.setText("Profesor");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 - Todos los estados", "1 - Abierto", "2 - En curso", "3 - Finalizado", " " }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado");

        jbAsistencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbAsistencia.setText("Asistencia");
        jbAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAsistenciaActionPerformed(evt);
            }
        });

        jbGenerarAsistencia.setText("Genera Asistencia");
        jbGenerarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarAsistenciaActionPerformed(evt);
            }
        });

        cmbCarrera.insertItemAt("0 - Todas las Carreras", 0);
        cmbMateria.insertItemAt("0 - Todas las Materias", 0);
        cmbProfesor.insertItemAt("0 - Todos los Profesores", 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(50, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299)
                        .addComponent(jbGenerarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbCuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jbAsistencia))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbEditar)
                                .addComponent(jbBorrar)))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbGenerarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbCarrera, cmbCuatrimestre, cmbEstado, cmbMateria, cmbProfesor});

        cmbCarrera.setSelectedIndex(0);
        cmbMateria.setSelectedIndex(0);
        cmbProfesor.setSelectedIndex(0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCursosMouseClicked
        jbBorrar.setEnabled(true);
        jbEditar.setEnabled(true);
        jbGenerarAsistencia.setEnabled(true);

        if (evt.getClickCount() > 1)       
        {
            this.editar();
        }
    }//GEN-LAST:event_jtCursosMouseClicked

     private Curso armarObjetoCurso(int r){
         Curso c = new Curso();
                 
        c.setIdCurso((int) jtCursos.getModel().getValueAt(r, 0));       
        c.setAnioLectivo((int) jtCursos.getModel().getValueAt(r, 3)); 
        c.setCuatrimestre(jtCursos.getModel().getValueAt(r, 4).toString());
        c.setComision(jtCursos.getModel().getValueAt(r, 5).toString());        
        c.setEstado(jtCursos.getModel().getValueAt(r, 7).toString());
        c.setCantidadInscriptos((int) jtCursos.getModel().getValueAt(r, 8));
        c.setDesde((Date) jtCursos.getModel().getValueAt(r, 9));
        c.setHasta((Date) jtCursos.getModel().getValueAt(r, 10));
        c.setCarreraMaterias((CarreraMateria)jtCursos.getModel().getValueAt(r, 11));
        c.setProfesor((Profesor) jtCursos.getModel().getValueAt(r, 6));
         
         return c;
     }
     
     private void agregar(){
        AgregarCursoUI agregarCursoUI = new AgregarCursoUI(null,true,"AGREGAR");
        agregarCursoUI.setLocationRelativeTo(null);        
        agregarCursoUI.setVisible(true);
        
        if(agregarCursoUI.isGrabo()){
            JOptionPane.showMessageDialog(null, "Se ha añadido exitosamente");
            this.cargarGrilla();  
        }      
     }
     
     private void cerrar(){
       this.dispose();
     }
     
      private void editar(){
            //obtiene el curso seleccionado
            int r = jtCursos.getSelectedRow();
            if (r != -1) {            
                Curso c = this.armarObjetoCurso(r);
                AgregarCursoUI modificarCursoUI = new AgregarCursoUI(null, true, "EDITAR",c);
                modificarCursoUI.setLocationRelativeTo(null); 
                modificarCursoUI.setVisible(true);
                if (modificarCursoUI.isGrabo()) {
                    JOptionPane.showMessageDialog(null, "Se ha editado exitosamente el curso");
                    this.cargarGrilla();
                }
            }
            else {
                    JOptionPane.showMessageDialog(null, "Error al intentar editadar el curso ");
                }             
      }
      
      private void borrar(){
          //obtiene el curso seleccionado
            int r = jtCursos.getSelectedRow();
            if (r != -1) {
                
                CursoDAO cDAO = new CursoDAO();
                Curso c = this.armarObjetoCurso(r);
                int confirmDialog=JOptionPane.showConfirmDialog(this,"¿Esta seguro que desea eliminar el curso?" +  + JOptionPane.YES_NO_OPTION);
                    if(confirmDialog == JOptionPane.YES_OPTION){
                        
                        int existeFK = cDAO.ExisteFkACurso(c);
                        
                        if(existeFK == 0){
                            cDAO.BorrarCurso(c);
                            JOptionPane.showMessageDialog(null, "Se ha eliminado exitosamente");                        
                            this.cargarGrilla();
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "No se puede eliminar el curso existen objetos asociados al mismo");   
                        }
                                                
                    }
            }
      }
      
    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        this.borrar();
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
      this.editar();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
       this.agregar();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void cmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarreraActionPerformed
        // TODO add your handling code here:
        this.cargarGrillaByFilters();
    }//GEN-LAST:event_cmbCarreraActionPerformed

    private void cmbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMateriaActionPerformed
        // TODO add your handling code here:
        this.cargarGrillaByFilters();
    }//GEN-LAST:event_cmbMateriaActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
         this.cargarGrillaByFilters();
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void cmbProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProfesorActionPerformed
        // TODO add your handling code here:
        this.cargarGrillaByFilters();
    }//GEN-LAST:event_cmbProfesorActionPerformed

    private void jbAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAsistenciaActionPerformed
        // TODO add your handling code here:
 
        int r = jtCursos.getSelectedRow();
        if (r != -1) {            
            Curso c = this.armarObjetoCurso(r);
            AsistenciaClaseDialog asistenciaClaseDialog = new AsistenciaClaseDialog(new javax.swing.JFrame(), true, c);
            asistenciaClaseDialog.setVisible(true);

        }
     
        
    }//GEN-LAST:event_jbAsistenciaActionPerformed

    private void jbGenerarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarAsistenciaActionPerformed
        // TODO add your handling code here:
        int r = jtCursos.getSelectedRow();
        int retorno;
        if (r  != -1 ){
            Curso curso = new Curso();
            curso.setIdCurso((int) jtCursos.getModel().getValueAt(r, 0));
            AsistenciaClaseDAO asistenciaClaseDAO = new AsistenciaClaseDAO();
            retorno = asistenciaClaseDAO.generarAsistencia(curso);
            if (retorno==1){
                JOptionPane.showMessageDialog(this, "Se ha generado asistencia exitosamente");
            }
            else{
                JOptionPane.showMessageDialog(this,"Error al generar asistencia","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbGenerarAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ABMCurso dialog = new ABMCurso(new javax.swing.JFrame(), true, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbCuatrimestre;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbMateria;
    private javax.swing.JComboBox<String> cmbProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbAsistencia;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbGenerarAsistencia;
    private javax.swing.JTable jtCursos;
    // End of variables declaration//GEN-END:variables
}
