/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia.vista;



import ar.com.lujan.asistencia.database.ProfesorDAO;
import ar.com.lujan.asistencia.modelo.Profesor;
import ar.com.lujan.asistencia.modelo.ProfesorTableModel;
import ar.com.lujan.asistencia.service.ProfesorRN;
import java.util.Date;


/**
 *
 * @author usuario
 */
public class ABMProfesores extends javax.swing.JDialog {

    ProfesorRN profesorRN = new ProfesorRN();
    
    public ABMProfesores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }
 
   private void cargarGrilla(){
       jtProfesores.setModel(new ProfesorTableModel((new ProfesorDAO()).getProfesor()));
   }
   
   private void cerrar(){
       this.dispose();
   }
 
    private Profesor armarObjetoProfesor(int r){
        Profesor p = new Profesor();
        p.setIdProfesor((int) jtProfesores.getModel().getValueAt(r,0));
        p.setApellido((String)jtProfesores.getModel().getValueAt(r,1));
        p.setNombre((String)jtProfesores.getModel().getValueAt(r,2));
        p.setDni(Integer.parseInt(jtProfesores.getModel().getValueAt(r,3).toString()));
        p.setGenero((String)jtProfesores.getModel().getValueAt(r,4));
        p.setFechaDeNacimiento((Date)jtProfesores.getModel().getValueAt(r,5));
        p.setEmail((String)jtProfesores.getModel().getValueAt(r,6));
        p.setEstado((Boolean)jtProfesores.getModel().getValueAt(r,7));
        return p;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlProfesores = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtProfesores = new javax.swing.JTable();
        jbBorrar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM Profesores");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);

        jlProfesores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlProfesores.setText("Profesores");

        jtProfesores.setModel(new ProfesorTableModel((new ProfesorDAO()).getProfesor()));
        jtProfesores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProfesoresMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtProfesores);

        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jlProfesores))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBorrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlProfesores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbEditar)
                    .addComponent(jbBorrar))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProfesoresMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jtProfesoresMouseClicked

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
       
        int row = jtProfesores.getSelectedRow();
        
        if (row != -1){//Arma el objeto alumno con los datos de la fila
            Profesor p = this.armarObjetoProfesor(row);
            //Ejecuta el borrar alumno
            profesorRN.borrarProfesor(p);
            this.cargarGrilla();
        
        }
         
        
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        int r = jtProfesores.getSelectedRow();
        Profesor p;
        if (r != -1){
            //armar el objeto Alumno con los datos de la fila
            Profesor profesor=this.armarObjetoProfesor(r);
            //instanciar la ventana y pasarle el objeto alumno
            AgregarProfesorUI editarProfesorUI = new AgregarProfesorUI(null,true,"EDITAR",profesor);//el primero es la herencia, o sea, extiende de jFrame. el segundo es si es modal o no, si esta por encima de todo
            editarProfesorUI.setLocationRelativeTo(null); 
            editarProfesorUI.setVisible(true);
            if (editarProfesorUI.isGrabo()) {
                this.cargarGrilla();
            }
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    
    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        AgregarProfesorUI agregarProfesorUI = new AgregarProfesorUI(null,true,"AGREGAR");//el primero es la herencia, o sea, extiende de jFrame. el segundo es si es modal o no
        agregarProfesorUI.setLocationRelativeTo(null);
        agregarProfesorUI.setOperacion("AGREGAR");
        agregarProfesorUI.setVisible(true);
        this.cargarGrilla(); 
        
        
        
    }//GEN-LAST:event_jbAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ABMProfesores dialog = new ABMProfesores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    //Variables Personalizadas
    private Profesor profesor;
    private boolean grabo = false;
    private String operacion;
   
    public String getOperacion() {
        return operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    
    public Profesor getProfesor() {
        return profesor;
    }
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    
    public boolean isGrabo() {
        return grabo;
    }

    public void setGrabo(boolean Grabo) {
        this.grabo = Grabo;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JLabel jlProfesores;
    private javax.swing.JTable jtProfesores;
    // End of variables declaration//GEN-END:variables
}
