/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia.vista;

import ar.com.lujan.asistencia.database.CarreraDAO;
import ar.com.lujan.asistencia.database.MateriaDAO;
import ar.com.lujan.asistencia.modelo.Materia;
import javax.swing.JOptionPane;

/**
 *
 * @author Papa
 */
public class AltaMateriaUI extends javax.swing.JDialog {

    /**
     * Creates new form AltaMateriaUI
     */
    public AltaMateriaUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AltaMateriaUI(java.awt.Frame parent, boolean modal, Materia c) {
        super(parent, modal);
        initComponents();
        
        this.setvMateria(c);
        

        //cargo la Descripcion de la carrera
        this.txtDescripcion.setText(c.getDescripcion());
        this.txtDescripcion.selectAll();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDescripcion.setText("Materia:");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // TODO add your handling code here:

        // Se Controla que el campo no esté en blanco
        String descripcion = txtDescripcion.getText();
        descripcion = descripcion.replaceAll(" ", "");
        if (descripcion.isEmpty()){
            JOptionPane.showMessageDialog(this,"Debe completar el campo Materia");
            this.txtDescripcion.requestFocus();
            this.txtDescripcion.selectAll();
        }
        else {
            if (this.getOperacion().equals("M")){

                this.getvMateria().setDescripcion(txtDescripcion.getText().toString());
//
                if ((new MateriaDAO()).getMateriasByDescripcion(this.getvMateria()).size() != 0){
                    JOptionPane.showMessageDialog(null, "Ya existe una materia con esta Descripción");
                    //cargo la Descripcion de la carrera
                    this.txtDescripcion.requestFocus();
                    this.txtDescripcion.selectAll();
                }
                else {
//
                    if ((new MateriaDAO()).ActualizarMateria(this.getvMateria()) == 1) {
                        JOptionPane.showMessageDialog(null, "La actualización fue exitosa");
                        this.setGrabo(true);
                        this.dispose();
                    } else
                        JOptionPane.showMessageDialog(this,"Error");
                }
            }

            if (this.getOperacion().equals("A")) {

                Materia c = new Materia();
                c.setDescripcion(txtDescripcion.getText().toString());
//
                if ((new MateriaDAO()).getMateriasByDescripcion(c).size() != 0){
                    JOptionPane.showMessageDialog(null, "Ya existe una materia con esta Descripción");
                    //cargo la Descripcion de la carrera
                    this.txtDescripcion.requestFocus();
                    this.txtDescripcion.selectAll();
                }
                else {
//
                    if ((new MateriaDAO()).insertarMateria(c) == 1) {
                        JOptionPane.showMessageDialog(null, "El ingreso fue exitoso");
                        this.setGrabo(true);
                        this.dispose();
                    } else
                        JOptionPane.showMessageDialog(this,"Error");
                }
            }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaMateriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaMateriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaMateriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaMateriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaMateriaUI dialog = new AltaMateriaUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
    private boolean grabo = false;
    private String operacion;
    private Materia vMateria;

    public Materia getvMateria() {
        return vMateria;
    }

    public void setvMateria(Materia vMateria) {
        this.vMateria = vMateria;
    }

    public String getOperacion() {
        return operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    public boolean isGrabo() {
        return grabo;
    }

    public void setGrabo(boolean grabo) {
        this.grabo = grabo;
    }

}
