/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia.vista;

import ar.com.lujan.asistencia.database.CarreraDAO;
import ar.com.lujan.asistencia.database.CarreraMateriaDAO;
import ar.com.lujan.asistencia.database.MateriaDAO;
import ar.com.lujan.asistencia.modelo.Carrera;
import ar.com.lujan.asistencia.modelo.CarreraMateria;
import ar.com.lujan.asistencia.modelo.Materia;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author impztz
 */
public class AltaCarreraMateriaUI extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public AltaCarreraMateriaUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        this.cmbCarrera.setModel(new DefaultComboBoxModel( (new CarreraDAO()).getCarreras().toArray()));
         cmbCarrera.insertItemAt("Seleccione una Carrera", 0);
        cmbCarrera.setSelectedIndex(0); 
    }

    public AltaCarreraMateriaUI(java.awt.Frame parent, boolean modal, CarreraMateria cm) {
        super(parent, modal);
        initComponents();
        
        this.setvCarreraMateria(cm);
        
        //cargo la carrera en el combo
        ArrayList<Carrera> carreras = new ArrayList<Carrera>();
        Carrera carrera = new Carrera();
        carrera.setIdCarrera(cm.getCarrera().getIdCarrera());
        carrera.setDescripcion(cm.getCarrera().getDescripcion());
        carreras.add(carrera);
        this.cmbCarrera.setModel(new DefaultComboBoxModel( carreras.toArray()));
        
        
        //cargo al materia en el combo
        ArrayList<Materia> materias = new ArrayList<Materia>();
        Materia materia = new Materia();
        materia.setIdMateria(cm.getMateria().getIdMateria());
        materia.setDescripcion(cm.getMateria().getDescripcion());
        materias.add(materia);
        this.cmbMateria.setModel(new DefaultComboBoxModel(materias.toArray()));
       
        
        //cargo la nota
        this.jAnioCarrera.setValue(cm.getAnioCarrera());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        lblMateria = new javax.swing.JLabel();
        cmbMateria = new javax.swing.JComboBox<>();
        lblCarrera = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        lblAnio = new javax.swing.JLabel();
        jAnioCarrera = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Materias para una Carrera");
        setModal(true);
        setResizable(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        lblMateria.setText("Materia: ");

        cmbMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMateriaActionPerformed(evt);
            }
        });

        lblCarrera.setText("Carrera:");

        cmbCarrera.setModel(new DefaultComboBoxModel( (new CarreraDAO()).getCarreras().toArray())
        );
        cmbCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarreraActionPerformed(evt);
            }
        });

        lblAnio.setText("Año:");

        jAnioCarrera.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
        jAnioCarrera.setValue(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnio)
                        .addGap(18, 18, 18)
                        .addComponent(jAnioCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMateria)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarrera)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateria)
                    .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnio)
                    .addComponent(jAnioCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGrabar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Alta De Materias en una Carrera");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (this.getOperacion().equals("M")){
            
            this.setCarrera((Carrera) cmbCarrera.getSelectedItem());
            this.setMateria((Materia) cmbMateria.getSelectedItem());

          
            this.getvCarreraMateria().setAnioCarrera(Integer.parseInt(jAnioCarrera.getValue().toString()));
            if ((new CarreraMateriaDAO()).ActualizarCarreraMateria(this.getvCarreraMateria()) == 1) {
                JOptionPane.showMessageDialog(null, "La actualización fue exitosa");
                this.setGrabo(true);
                this.dispose();
            } else
                JOptionPane.showMessageDialog(this,"Error");
        }
        
        
        if (this.getOperacion().equals("A")) {
     
            if (cmbCarrera.getSelectedIndex() != 0  ) {

                this.setCarrera((Carrera) cmbCarrera.getSelectedItem());
                this.setMateria((Materia) cmbMateria.getSelectedItem());

                CarreraMateria cm = new CarreraMateria();
                Carrera c = new Carrera();
                Materia m = new Materia();
                
                c.setIdCarrera(this.getCarrera().getIdCarrera());
                c.setDescripcion(this.getCarrera().getDescripcion());
                m.setIdMateria(this.getMateria().getIdMateria());
                m.setDescripcion(this.getMateria().getDescripcion());
                cm.setCarrera(c);
                cm.setMateria(m);
                cm.setAnioCarrera(Integer.parseInt(jAnioCarrera.getValue().toString()));
                if ((new CarreraMateriaDAO()).insertarCarreraMateria(cm) == 1) {
                    JOptionPane.showMessageDialog(null, "El ingreso fue exitoso");
                    this.setGrabo(true);
                    this.dispose();
                } else
                    JOptionPane.showMessageDialog(this,"Error");
            }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void cmbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMateriaActionPerformed

    }//GEN-LAST:event_cmbMateriaActionPerformed

    private void cmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarreraActionPerformed
        
        if (cmbCarrera.getSelectedIndex() != 0) {
            Carrera carrera = (Carrera) cmbCarrera.getSelectedItem();
            //cmbMateria.setModel(new DefaultComboBoxModel( (new MateriaDAO()).getMaterias().toArray()));
            cmbMateria.setModel(new DefaultComboBoxModel( (new CarreraMateriaDAO()).getMateriasNoCarrera(carrera).toArray()));
        } 
  //      else
  //          if (this.operacion.equals("A"))
  //              cmbMateria.setModel(new DefaultComboBoxModel());
    }//GEN-LAST:event_cmbCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCarreraMateriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCarreraMateriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCarreraMateriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCarreraMateriaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaCarreraMateriaUI dialog = new AltaCarreraMateriaUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbMateria;
    private javax.swing.JSpinner jAnioCarrera;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblMateria;
    // End of variables declaration//GEN-END:variables
    private boolean grabo = false;
    private Carrera carrera ;
    private Materia materia;
    private String operacion;
    private CarreraMateria vCarreraMateria;

    public CarreraMateria getvCarreraMateria() {
        return vCarreraMateria;
    }

    public void setvCarreraMateria(CarreraMateria vCarreraMateria) {
        this.vCarreraMateria = vCarreraMateria;
    }

    public String getOperacion() {
        return operacion;
    }

    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    public Carrera getCarrera() {
        return carrera;
    }

    public Materia getMateria() {
        return materia;
    }

    public void setMateria(Materia materia) {
        this.materia = materia;
    }

    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    public boolean isGrabo() {
        return grabo;
    }

    public void setGrabo(boolean grabo) {
        this.grabo = grabo;
    }
}
