/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia.vista;

import ar.com.lujan.asistencia.database.CarreraDAO;
import ar.com.lujan.asistencia.database.CarreraMateriaDAO;
import ar.com.lujan.asistencia.database.CursoDAO;
import ar.com.lujan.asistencia.database.MateriaDAO;
import ar.com.lujan.asistencia.modelo.Carrera;
import ar.com.lujan.asistencia.modelo.CarreraMateria;
import ar.com.lujan.asistencia.modelo.CarreraMateriaTableModel;
import ar.com.lujan.asistencia.modelo.Materia;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Papa
 */
public class CarreraMateriaDialog extends javax.swing.JDialog {

    /**
     * Creates new form CarreraMateriaDialog
     */
    public CarreraMateriaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CarreraMateriaTableModel cMTM = new CarreraMateriaTableModel((new CarreraMateriaDAO()).getCarreraMateria());
        this.tblCarreraMateria.setModel(cMTM);

        // Se ocultan las columnas que contienen ID
        tblCarreraMateria.getColumnModel().getColumn(0).setMaxWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(0).setMinWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(1).setMaxWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(1).setMinWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(2).setMaxWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(2).setMinWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
    
        // Tamaño de las columnsa visibles
         tblCarreraMateria.getColumnModel().getColumn(3).setPreferredWidth(300);
         tblCarreraMateria.getColumnModel().getColumn(4).setPreferredWidth(390);
         tblCarreraMateria.getColumnModel().getColumn(5).setPreferredWidth(70);

         // Evita que se pueda cambiar de posición las columnas 
         tblCarreraMateria.getTableHeader().setReorderingAllowed(false) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void cargarGrillaByFilters(){
        if (cmbCarrera.getSelectedIndex()==0 && cmbMateria.getSelectedIndex()==0)
            tblCarreraMateria.setModel(new CarreraMateriaTableModel((new CarreraMateriaDAO()).getCarreraMateria())
        );
        if (cmbCarrera.getSelectedIndex()!=0 && cmbMateria.getSelectedIndex()==0) {
            Carrera carrera = (Carrera) cmbCarrera.getSelectedItem();
            tblCarreraMateria.setModel(new CarreraMateriaTableModel((new CarreraMateriaDAO()).getMateriasByCarrera(carrera)));
        }
        if (cmbCarrera.getSelectedIndex()!=0 && cmbMateria.getSelectedIndex()!=0) {
            Carrera carrera = (Carrera) cmbCarrera.getSelectedItem();
            Materia materia = (Materia) cmbMateria.getSelectedItem();
            tblCarreraMateria.setModel(new CarreraMateriaTableModel((new CarreraMateriaDAO()).getCarreraMateria(carrera, materia)));
        }
        if (cmbCarrera.getSelectedIndex()==0 && cmbMateria.getSelectedIndex()!=0) {
            Materia materia = (Materia) cmbMateria.getSelectedItem();
            tblCarreraMateria.setModel(new CarreraMateriaTableModel((new CarreraMateriaDAO()).getCarrerasByMateria(materia)));
        }
         
        // Se ocultan las columnas que contiene ID 
        tblCarreraMateria.getColumnModel().getColumn(0).setMaxWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(0).setMinWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(1).setMaxWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(1).setMinWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(1).setMinWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(2).setMaxWidth(0);
        tblCarreraMateria.getColumnModel().getColumn(2).setMinWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
        tblCarreraMateria.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
        // Tamaño de las columnsa visibles
         tblCarreraMateria.getColumnModel().getColumn(3).setPreferredWidth(300);
         tblCarreraMateria.getColumnModel().getColumn(4).setPreferredWidth(390);
         tblCarreraMateria.getColumnModel().getColumn(5).setPreferredWidth(70);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarreraMateria = new javax.swing.JTable();
        cmbCarrera = new javax.swing.JComboBox<>();
        lblCarrera = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        cmbMateria = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM - Materias por Carreras");
        setResizable(false);

        tblCarreraMateria.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblCarreraMateria);

        cmbCarrera.setModel(new DefaultComboBoxModel( (new CarreraDAO()).getCarreras().toArray()));
        cmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarreraActionPerformed(evt);
            }
        });

        lblCarrera.setText("Carrera");

        lblMateria.setText("Materia");

        cmbMateria.setModel(new DefaultComboBoxModel( (new MateriaDAO()).getMaterias().toArray()));
        cmbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMateriaActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        cmbCarrera.insertItemAt(" Todas las Carreras", 0);
        cmbMateria.insertItemAt(" Todas las Materias", 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMateria)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarrera)
                    .addComponent(lblMateria)
                    .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar))
                .addContainerGap())
        );

        cmbCarrera.setSelectedIndex(0);
        cmbMateria.setSelectedIndex(0);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarreraActionPerformed
        // TODO add your handling code here:
        this.cargarGrillaByFilters();
    }//GEN-LAST:event_cmbCarreraActionPerformed

    private void cmbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMateriaActionPerformed
        // TODO add your handling code here:
        this.cargarGrillaByFilters();
    }//GEN-LAST:event_cmbMateriaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        AltaCarreraMateriaUI altaCarreraMateria = new AltaCarreraMateriaUI(new javax.swing.JFrame(), true);
        altaCarreraMateria.setOperacion("A");
        altaCarreraMateria.setLocationRelativeTo(this);
        altaCarreraMateria.setVisible(true);
        if (altaCarreraMateria.isGrabo()) {
            this.cargarGrillaByFilters();        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        AltaCarreraMateriaUI fmod;
        
        int row = tblCarreraMateria.getSelectedRow();
        if (row != -1){
            CarreraMateria cm = new CarreraMateria();
            Carrera c = new Carrera();
            Materia m = new Materia();
            //COLUMNAS={"id", "Materia", "Apellido", "nota","idAlumno", "idMateria"};
                        
            cm.setIdCarreraMateria((int)tblCarreraMateria.getModel().getValueAt(row, 0));
            c.setIdCarrera((int)tblCarreraMateria.getModel().getValueAt(row, 1));
            m.setIdMateria((int)tblCarreraMateria.getModel().getValueAt(row, 2));
            c.setDescripcion((String)tblCarreraMateria.getModel().getValueAt(row, 3).toString());
            m.setDescripcion((String)tblCarreraMateria.getModel().getValueAt(row, 4).toString());
            cm.setCarrera(c);
            cm.setMateria(m);
            cm.setAnioCarrera((int) tblCarreraMateria.getModel().getValueAt(row, 5));
            
            fmod   = new AltaCarreraMateriaUI(new javax.swing.JFrame(), true, cm);
            fmod.setOperacion("M");
            fmod.setLocationRelativeTo(this);
            fmod.setVisible(true);
            if (fmod.isGrabo()) {
                this.cargarGrillaByFilters();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Carrera Materia");
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
                int row = tblCarreraMateria.getSelectedRow();
        if (row != -1){
            CarreraMateria cm = new CarreraMateria();
            Carrera c = new Carrera();
            Materia m = new Materia();
            //COLUMNAS={"id", "Materia", "Apellido", "nota","idAlumno", "idMateria"};
            
            cm.setIdCarreraMateria((int)tblCarreraMateria.getModel().getValueAt(row, 0));
            c.setIdCarrera((int)tblCarreraMateria.getModel().getValueAt(row, 1));
            m.setIdMateria((int)tblCarreraMateria.getModel().getValueAt(row, 2));
            c.setDescripcion((String)tblCarreraMateria.getModel().getValueAt(row, 3).toString());
            m.setDescripcion((String)tblCarreraMateria.getModel().getValueAt(row, 4).toString());
            cm.setCarrera(c);
            cm.setMateria(m);
            cm.setAnioCarrera((int) tblCarreraMateria.getModel().getValueAt(row, 5));
            

            // Se verifica si la Carrera-Materia está asociada a algun Curso
            if ((new CursoDAO()).getCursosByCarreraMateria(cm).size() != 0){
//            if ((new CursoDAO()).getCursosByCarreraMateria(c, m).size() != 0){
                JOptionPane.showMessageDialog(null, "La Carrera - Materia no se puede borrar ya que está asociada a uno o más Cursos");
            }
            else {
 
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog (this, "¿Confirma la eliminación de la relación Carrera - Materia: \"" + cm.getCarrera().getDescripcion() + " - " + cm.getMateria().getDescripcion()+ "\" de " + cm.getAnioCarrera() + " Año? " ,"Borrar Carrera - Materia",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    if ((new CarreraMateriaDAO()).BorrarCarreraMateria(cm)==1)
                        this.cargarGrillaByFilters();
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Carrera Materia");
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarreraMateriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarreraMateriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarreraMateriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarreraMateriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarreraMateriaDialog dialog = new CarreraMateriaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbMateria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JTable tblCarreraMateria;
    // End of variables declaration//GEN-END:variables
}
