/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia.vista;

import ar.com.lujan.asistencia.database.CarreraDAO;
import ar.com.lujan.asistencia.database.CarreraMateriaDAO;
import ar.com.lujan.asistencia.modelo.Carrera;
import ar.com.lujan.asistencia.modelo.CarreraTableModel;
import javax.swing.JOptionPane;
//import javax.swing.SwingConstants;
//import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Papa
 */
public class CarreraDialog extends javax.swing.JDialog {

    // Para alinear tabla
    //private static DefaultTableCellRenderer tcr;

    /**
     * Creates new form CarreraDialog
     */
    public CarreraDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CarreraTableModel c = new CarreraTableModel((new CarreraDAO()).getCarreras());
        this.tblCarreras.setModel(c);
        // Se ocultan las columnas que contiene ID 
        tblCarreras.getColumnModel().getColumn(0).setMaxWidth(0);
        tblCarreras.getColumnModel().getColumn(0).setMinWidth(0);
        tblCarreras.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblCarreras.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        // Evita que se pueda cambiar de posición las columnas 
        tblCarreras.getTableHeader().setReorderingAllowed(false) ;

        //
        //Indicamos la alineacion de las columnas
//        tcr = new DefaultTableCellRenderer();
//        tcr.setHorizontalAlignment(SwingConstants.CENTER); //CENTER o LEFT
        //Indico la columna que quiero alinear siendo 1 el numero de columna
//        tblCarreras.getTableHeader().getColumnModel().getColumn(1).setCellRenderer(tcr);
//        tcr.setHorizontalAlignment(SwingConstants.LEFT); //CENTER o LEFT
//        tblCarreras.getColumnModel().getColumn(1).setCellRenderer(tcr);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        private void cargarGrillaByFilters(){
            tblCarreras.setModel(new CarreraTableModel((new CarreraDAO()).getCarreras()));
        // Se ocultan las columnas que contiene ID 
            tblCarreras.getColumnModel().getColumn(0).setMaxWidth(0);
            tblCarreras.getColumnModel().getColumn(0).setMinWidth(0);
            tblCarreras.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tblCarreras.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarreras = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM - Carreras");
        setResizable(false);

        tblCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCarreras);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        AltaCarreraUI altaCarrera = new AltaCarreraUI(new javax.swing.JFrame(), true);
        altaCarrera.setOperacion("A");
        altaCarrera.setLocationRelativeTo(this);
        altaCarrera.setVisible(true);
        if (altaCarrera.isGrabo()) {
//             tblCarreraMateria.setModel(new CarreraMateriaTableModel((new CarreraMateriaDAO()).getMateriasByCarrera(altaCarreraFinal.getCarrera())));
            this.cargarGrillaByFilters();        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        AltaCarreraUI fmod;
        
        int row = tblCarreras.getSelectedRow();
        if (row != -1){
            Carrera c = new Carrera();
            //COLUMNAS={"id", "Materia", "Apellido", "nota","idAlumno", "idMateria"};
            
            c.setIdCarrera((int)tblCarreras.getModel().getValueAt(row, 0));
            c.setDescripcion((String)tblCarreras.getModel().getValueAt(row, 1).toString());
            
            fmod   = new AltaCarreraUI(new javax.swing.JFrame(), true, c);
            fmod.setOperacion("M");
            fmod.setLocationRelativeTo(this);
            fmod.setVisible(true);
            if (fmod.isGrabo()) {
                //tblCarreraMateria.setModel(new CarreraMateriaTableModel((new CarreraMateriaDAO()).getMateriasByCarrera(fmod.getCarrera())));
                this.cargarGrillaByFilters();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Carrera");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int row = tblCarreras.getSelectedRow();
        if (row != -1){
            Carrera c = new Carrera();
            //COLUMNAS={"id", "Materia", "Apellido", "nota","idAlumno", "idMateria"};
            
            c.setIdCarrera((int)tblCarreras.getModel().getValueAt(row, 0));
            c.setDescripcion((String)tblCarreras.getModel().getValueAt(row, 1).toString());

            // Se verifica si la Carrera está asociada a alguna Materia
            if ((new CarreraMateriaDAO()).getMateriasByCarrera(c).size() != 0){
                JOptionPane.showMessageDialog(null, "La Carrera no se puede borrar ya que está asociada a una o más Materias");
            }
            else {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog (this, "¿Confirma la eliminación de la carrera \"" + c.getDescripcion() + "\"? ","Borrar Carrera",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    if ((new CarreraDAO()).BorrarCarrera(c)==1)
                        this.cargarGrillaByFilters();
                }            
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Carrera");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarreraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarreraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarreraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarreraDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarreraDialog dialog = new CarreraDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarreras;
    // End of variables declaration//GEN-END:variables
}
