/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia.vista;

import ar.com.lujan.asistencia.database.AsistenciaClaseDAO;
import ar.com.lujan.asistencia.database.CarreraDAO;
import ar.com.lujan.asistencia.database.CarreraMateriaDAO;
import ar.com.lujan.asistencia.database.CursoAlumnosDAO;
import ar.com.lujan.asistencia.database.CursoDAO;
import ar.com.lujan.asistencia.modelo.Alumno;
import ar.com.lujan.asistencia.modelo.Carrera;
import ar.com.lujan.asistencia.modelo.CarreraMateria;
import ar.com.lujan.asistencia.modelo.Curso;
import ar.com.lujan.asistencia.modelo.CursoAlumno;
import ar.com.lujan.asistencia.modelo.CursoAlumnosTableModel;
import ar.com.lujan.asistencia.modelo.CursoTableModel;


import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author geragonzalez
 */
public class CursoAlumnos extends javax.swing.JDialog {

    /**
     * Creates new form CursoAlumnos
     */
    public CursoAlumnos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cmbCarrera.setModel(new DefaultComboBoxModel( (new CarreraDAO()).getCarreras().toArray()));
        cmbCarrera.insertItemAt("Seleccione una Carrera", 0);
        cmbCarrera.setSelectedIndex(0); 
        jtCursos.setModel(new CursoTableModel( new ArrayList<>()));
        jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
        jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
        jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
        jtCursoAlumnos.setModel(new CursoAlumnosTableModel( new ArrayList<>()));
        jtAlumnos.setModel(new CursoAlumnosTableModel ( new ArrayList<>()));
        jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
        jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
        jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
        jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCarrera = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        lblMateria = new javax.swing.JLabel();
        cmbMateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCursos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCursoAlumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtAlumnos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbGenerarAsistencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asociar alumnos a un Curso");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCarrera.setText("Carrera");

        cmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarreraActionPerformed(evt);
            }
        });

        lblMateria.setText("Materia");

        cmbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMateriaActionPerformed(evt);
            }
        });

        jtCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCursos);

        cmbCarrera.insertItemAt("0 - Todas las Carreras", 0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCarrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarrera)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateria)
                    .addComponent(cmbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cmbCarrera.setSelectedIndex(0);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setViewportView(jtCursoAlumnos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alumnos Inscriptos al Curso");

        jScrollPane3.setViewportView(jtAlumnos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alumnos que pueden Asistir al Curso");

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/lujan/asistencia/vista/if_Go_back_132769.png"))); // NOI18N
        jbAgregar.setText(" Agregar");
        jbAgregar.setToolTipText("");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/lujan/asistencia/vista/if_Go_forward_132792.png"))); // NOI18N
        jButton1.setText(" Quitar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jbGenerarAsistencia.setText("Genera Asistencia");
        jbGenerarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbGenerarAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGenerarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarreraActionPerformed
        if (cmbCarrera.getSelectedIndex() != 0) {
            Carrera carrera = (Carrera) cmbCarrera.getSelectedItem();    
            cmbMateria.setModel(new DefaultComboBoxModel( (new CarreraMateriaDAO()).getMateriasByCarrera(carrera).toArray()));
            cmbMateria.insertItemAt("Seleccione una Materia", 0);
            cmbMateria.setSelectedIndex(0);
        } else {
            cmbMateria.setModel(new DefaultComboBoxModel( ));
            jtCursos.setModel(new CursoTableModel( new ArrayList<>()));
            jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
            jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
            jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
            jtCursoAlumnos.setModel(new CursoAlumnosTableModel( new ArrayList<>()));
            jtAlumnos.setModel(new CursoAlumnosTableModel( new ArrayList<>())); 
            jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
            jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
            jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
            jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
        }

        jLabel3.setText("Total de Inscriptos: " + jtCursoAlumnos.getModel().getRowCount());
        jLabel4.setText("Total de Alumnos: " + jtAlumnos.getModel().getRowCount());
        
    }//GEN-LAST:event_cmbCarreraActionPerformed

    private void cmbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMateriaActionPerformed
        // TODO add your handling code here:
        if (cmbMateria.getSelectedIndex() != 0) {            
            CarreraMateria carreraMateria = (CarreraMateria) cmbMateria.getSelectedItem();
            jtCursos.setModel(new CursoTableModel( (new CursoDAO()).getCursosByCarreraMateria(carreraMateria) ));
         
        } else {
            jtCursos.setModel(new CursoTableModel( new ArrayList<>()));
           
        }
        jtCursoAlumnos.setModel(new CursoAlumnosTableModel( new ArrayList<>()));
        jtAlumnos.setModel(new CursoAlumnosTableModel( new ArrayList<>()));
        jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
        jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
        jtCursos.removeColumn(jtCursos.getColumnModel().getColumn(0));
        jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
        jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
        jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
        jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
        jLabel3.setText("Total de Inscriptos: " + jtCursoAlumnos.getModel().getRowCount());
        jLabel4.setText("Total de Alumnos: " + jtAlumnos.getModel().getRowCount());
    }//GEN-LAST:event_cmbMateriaActionPerformed

    private void jtCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCursosMouseClicked
        int r = jtCursos.getSelectedRow();
        if (r  != -1 ){
            Curso curso = new Curso();
            curso.setIdCurso((int) jtCursos.getModel().getValueAt(r, 0));
            CursoAlumnosDAO cursoAlumnoDAO = new CursoAlumnosDAO();
            jtCursoAlumnos.setModel( new CursoAlumnosTableModel( cursoAlumnoDAO.getCursoAlumnos(curso)));
            jtAlumnos.setModel(new CursoAlumnosTableModel( cursoAlumnoDAO.getAlumnoNoEstanEnCurso(curso)));
            jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
            jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
            jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
            jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
            jLabel3.setText("Total de Inscriptos: " + jtCursoAlumnos.getModel().getRowCount());
            jLabel4.setText("Total de Alumnos: " + jtAlumnos.getModel().getRowCount());
           
        } 
    }//GEN-LAST:event_jtCursosMouseClicked

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        int r[] = jtAlumnos.getSelectedRows();
        Curso curso = new Curso();
        for (int i=0; i< r.length; i ++){
            CursoAlumno cursoAlumno = new CursoAlumno();
            if (i == 0 ) curso.setIdCurso((int) jtAlumnos.getModel().getValueAt(r[i], 0));
            Alumno alumno = new Alumno();
            alumno.setID((int) jtAlumnos.getModel().getValueAt(r[i], 1));
            cursoAlumno.setCurso(curso);
            cursoAlumno.setAlumno(alumno);
            CursoAlumnosDAO cursoAlumnosDAO =  new CursoAlumnosDAO();
            cursoAlumnosDAO.insertCursoAlumnos(cursoAlumno);
            cursoAlumnosDAO.ActualizarInscriptosAlCuros(curso);
        }  
        if (r.length > 0 ) {
              
            jtCursoAlumnos.setModel( new CursoAlumnosTableModel( (new CursoAlumnosDAO()).getCursoAlumnos(curso)));
            jtAlumnos.setModel(new CursoAlumnosTableModel( (new CursoAlumnosDAO()).getAlumnoNoEstanEnCurso(curso)));
            jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
            jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
            jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
            jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
            jLabel3.setText("Total de Inscriptos: " + jtCursoAlumnos.getModel().getRowCount());
            jLabel4.setText("Total de Alumnos: " + jtAlumnos.getModel().getRowCount());          
        }
        
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int r = jtCursoAlumnos.getSelectedRow();
        if (r  != -1 ){
            CursoAlumno cursoAlumno = new CursoAlumno();
            Curso curso = new Curso();
            Alumno alumno = new Alumno();
            curso.setIdCurso((int) jtCursoAlumnos.getModel().getValueAt(r, 0));
            alumno.setID((int) jtCursoAlumnos.getModel().getValueAt(r, 1));
            cursoAlumno.setCurso(curso);
            cursoAlumno.setAlumno(alumno);
            CursoAlumnosDAO cursoAlumnosDAO = new CursoAlumnosDAO();
            int clases = cursoAlumnosDAO.existeAsistencia(cursoAlumno); //cantidad de clases a la que el alumno se encuentra inscripto
            String mensaje = "El alumno tiene cargada asistencia en " + clases + " clases. ¿Desea quitarlo de todos modos?";
            if (clases>0){
                int confirmDialog = JOptionPane.showConfirmDialog(this, mensaje  , "Pregunta", JOptionPane.YES_NO_OPTION);
                if(confirmDialog == JOptionPane.YES_OPTION){
                    cursoAlumno.setIdCursoAlumno(cursoAlumnosDAO.getIdCursoAlumno(cursoAlumno));
                    cursoAlumnosDAO.DeleteCursoAlumnos(cursoAlumno);
                    cursoAlumnosDAO.ActualizarInscriptosAlCuros(curso);
                    jtCursoAlumnos.setModel( new CursoAlumnosTableModel( (new CursoAlumnosDAO()).getCursoAlumnos(curso)));
                    jtAlumnos.setModel(new CursoAlumnosTableModel( (new CursoAlumnosDAO()).getAlumnoNoEstanEnCurso(curso)));
                    jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
                    jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
                    jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
                    jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
                    jLabel3.setText("Total de Inscriptos: " + jtCursoAlumnos.getModel().getRowCount());
                    jLabel4.setText("Total de Alumnos: " + jtAlumnos.getModel().getRowCount());
                }
            }
            else{
                    cursoAlumnosDAO.DeleteCursoAlumnos(cursoAlumno);
                    cursoAlumnosDAO.ActualizarInscriptosAlCuros(curso);
                    jtCursoAlumnos.setModel( new CursoAlumnosTableModel( (new CursoAlumnosDAO()).getCursoAlumnos(curso)));
                    jtAlumnos.setModel(new CursoAlumnosTableModel( (new CursoAlumnosDAO()).getAlumnoNoEstanEnCurso(curso)));
                    jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
                    jtCursoAlumnos.removeColumn(jtCursoAlumnos.getColumnModel().getColumn(0));
                    jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
                    jtAlumnos.removeColumn(jtAlumnos.getColumnModel().getColumn(0));
                    jLabel3.setText("Total de Inscriptos: " + jtCursoAlumnos.getModel().getRowCount());
                    jLabel4.setText("Total de Alumnos: " + jtAlumnos.getModel().getRowCount());
            }
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbGenerarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarAsistenciaActionPerformed
        // TODO add your handling code here:
         int r = jtCursos.getSelectedRow();
         int retorno;
        if (r  != -1 ){
            Curso curso = new Curso();
            curso.setIdCurso((int) jtCursos.getModel().getValueAt(r, 0));
            AsistenciaClaseDAO asistenciaClaseDAO = new AsistenciaClaseDAO();
            retorno = asistenciaClaseDAO.generarAsistencia(curso);
            if (retorno==1){
                JOptionPane.showMessageDialog(this, "Se ha generado asistencia exitosamente");
            }
            else{
                JOptionPane.showMessageDialog(this,"Error al generar asistencia","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbGenerarAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CursoAlumnos dialog = new CursoAlumnos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbMateria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbGenerarAsistencia;
    private javax.swing.JTable jtAlumnos;
    private javax.swing.JTable jtCursoAlumnos;
    private javax.swing.JTable jtCursos;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblMateria;
    // End of variables declaration//GEN-END:variables
}
