/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia.vista;

import ar.com.lujan.asistencia.database.CarreraMateriaDAO;
import ar.com.lujan.asistencia.database.MateriaDAO;
import ar.com.lujan.asistencia.modelo.Materia;
import ar.com.lujan.asistencia.modelo.MateriaTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Papa
 */
public class MateriaDialog extends javax.swing.JDialog {

    /**
     * Creates new form MateriaDialog
     */
    public MateriaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        MateriaTableModel c = new MateriaTableModel((new MateriaDAO()).getMaterias());
        this.tblMaterias.setModel(c);
        // Se ocultan las columnas que contiene ID 
        tblMaterias.getColumnModel().getColumn(0).setMaxWidth(0);
        tblMaterias.getColumnModel().getColumn(0).setMinWidth(0);
        tblMaterias.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblMaterias.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        // Evita que se pueda cambiar de posición las columnas 
         tblMaterias.getTableHeader().setReorderingAllowed(false) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        private void cargarGrillaByFilters(){
            tblMaterias.setModel(new MateriaTableModel((new MateriaDAO()).getMaterias()));
            tblMaterias.getColumnModel().getColumn(0).setMaxWidth(0);
            tblMaterias.getColumnModel().getColumn(0).setMinWidth(0);
            tblMaterias.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tblMaterias.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM - Materias");
        setResizable(false);

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblMaterias);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        AltaMateriaUI altaMateria = new AltaMateriaUI(new javax.swing.JFrame(), true);
        altaMateria.setOperacion("A");
        altaMateria.setLocationRelativeTo(this);
        altaMateria.setVisible(true);
        if (altaMateria.isGrabo()) {
//             tblMateriaMateria.setModel(new MateriaMateriaTableModel((new MateriaMateriaDAO()).getMateriasByMateria(altaMateriaFinal.getMateria())));
            this.cargarGrillaByFilters();        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        AltaMateriaUI fmod;
        
        int row = tblMaterias.getSelectedRow();
        if (row != -1){
            Materia c = new Materia();
            //COLUMNAS={"id", "Materia", "Apellido", "nota","idAlumno", "idMateria"};
            
            c.setIdMateria((int)tblMaterias.getModel().getValueAt(row, 0));
            c.setDescripcion((String)tblMaterias.getModel().getValueAt(row, 1).toString());
            
            fmod   = new AltaMateriaUI(new javax.swing.JFrame(), true, c);
            fmod.setOperacion("M");
            fmod.setLocationRelativeTo(this);
            fmod.setVisible(true);
            if (fmod.isGrabo()) {
                //tblMateriaMateria.setModel(new MateriaMateriaTableModel((new MateriaMateriaDAO()).getMateriasByMateria(fmod.getMateria())));
                this.cargarGrillaByFilters();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Materia");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int row = tblMaterias.getSelectedRow();
        if (row != -1){
            Materia m = new Materia();
            //COLUMNAS={"id", "Materia", "Apellido", "nota","idAlumno", "idMateria"};
            
            m.setIdMateria((int)tblMaterias.getModel().getValueAt(row, 0));
            m.setDescripcion((String)tblMaterias.getModel().getValueAt(row, 1).toString());
            
            if ((new CarreraMateriaDAO()).getCarrerasByMateria(m).size() != 0){
                JOptionPane.showMessageDialog(null, "La Materia no se puede borrar ya que está asociada a una o más Carreras");
            }
            else {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog (null, "¿Confirma la eliminación de la materia \"" + m.getDescripcion() + "\"? ","Borrar Materia",dialogButton);
                if(dialogResult == JOptionPane.YES_OPTION){
                    if ((new MateriaDAO()).BorrarMateria(m)==1)
                        this.cargarGrillaByFilters();
                } 
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Materia");
        }
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MateriaDialog dialog = new MateriaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMaterias;
    // End of variables declaration//GEN-END:variables
}
