/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.lujan.asistencia;

import ar.com.lujan.asistencia.vista.ABMAlumnos;
import ar.com.lujan.asistencia.vista.ABMClases;
import ar.com.lujan.asistencia.vista.ABMCurso;
import ar.com.lujan.asistencia.vista.ABMCursoDia;
import ar.com.lujan.asistencia.vista.ABMProfesores;
import ar.com.lujan.asistencia.vista.AcercaDe;
import ar.com.lujan.asistencia.vista.AsistenciaClaseDialog;
import ar.com.lujan.asistencia.vista.CarreraDialog;
import ar.com.lujan.asistencia.vista.CarreraMateriaDialog;
import ar.com.lujan.asistencia.vista.CursoAlumnos;
import ar.com.lujan.asistencia.vista.Encriptador;
import ar.com.lujan.asistencia.vista.JPanelConFondo;
import ar.com.lujan.asistencia.vista.Login;
import ar.com.lujan.asistencia.vista.MateriaDialog;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author geragonzalez
 */
public class AsistenciaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AsistenciaJFrame
     */
    
      static{
        Login loginScreen = new Login(null,true);
        loginScreen.setLocationRelativeTo(null); 
        loginScreen.setVisible(true);
    }
    
    private final JPanelConFondo contenedor = new JPanelConFondo();
    
    public AsistenciaJFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Sistema de Asistencia");
        contenedor.setImagen("fondo.jpg");
        this.setContentPane(contenedor);
    }
    
 
    public void setImagen(String nombreImagen) {
        contenedor.setImagen(nombreImagen);
    }
 
    public void setImagen(Image nuevaImagen) {
        contenedor.setImagen(nuevaImagen);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMemuBar = new javax.swing.JMenuBar();
        jMenuABM = new javax.swing.JMenu();
        jMenuAlumno = new javax.swing.JMenuItem();
        jMenuCarrera = new javax.swing.JMenuItem();
        jMenuCarreraMaterias = new javax.swing.JMenuItem();
        jMenuCurso = new javax.swing.JMenuItem();
        jMenuCursoDias = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenuItem();
        jMenuProfesro = new javax.swing.JMenuItem();
        jMenuAsistencia = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuAlumnoCurso = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSistema = new javax.swing.JMenu();
        jMenuAcercaDe = new javax.swing.JMenuItem();
        jMenuEncriptador = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jMenuABM.setText("ABM");
        jMenuABM.setToolTipText("");

        jMenuAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAlumno.setText("Alumno");
        jMenuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlumnoActionPerformed(evt);
            }
        });
        jMenuABM.add(jMenuAlumno);

        jMenuCarrera.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCarrera.setText("Carrera");
        jMenuCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarreraActionPerformed(evt);
            }
        });
        jMenuABM.add(jMenuCarrera);

        jMenuCarreraMaterias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuCarreraMaterias.setText("Carrera - Materias");
        jMenuCarreraMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarreraMateriasActionPerformed(evt);
            }
        });
        jMenuABM.add(jMenuCarreraMaterias);

        jMenuCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCurso.setText("Curso");
        jMenuCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCursoActionPerformed(evt);
            }
        });
        jMenuABM.add(jMenuCurso);

        jMenuCursoDias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuCursoDias.setText("Curso Dias");
        jMenuCursoDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCursoDiasActionPerformed(evt);
            }
        });
        jMenuABM.add(jMenuCursoDias);

        jMenuMateria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuMateria.setText("Materia");
        jMenuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMateriaActionPerformed(evt);
            }
        });
        jMenuABM.add(jMenuMateria);

        jMenuProfesro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuProfesro.setText("Profesor");
        jMenuProfesro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProfesroActionPerformed(evt);
            }
        });
        jMenuABM.add(jMenuProfesro);

        jMemuBar.add(jMenuABM);

        jMenuAsistencia.setText("Asistencia");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItem3.setText("Asistencia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuAsistencia.add(jMenuItem3);

        jMenuAlumnoCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuAlumnoCurso.setText("Inscribir alumnos");
        jMenuAlumnoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlumnoCursoActionPerformed(evt);
            }
        });
        jMenuAsistencia.add(jMenuAlumnoCurso);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem1.setText("Libro de Temas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAsistencia.add(jMenuItem1);

        jMemuBar.add(jMenuAsistencia);

        jMenuSistema.setText("Sistema");

        jMenuAcercaDe.setText("Acerca De");
        jMenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAcercaDeActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuAcercaDe);

        jMenuEncriptador.setText("Encriptador");
        jMenuEncriptador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEncriptadorActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuEncriptador);

        jMenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuSalir);

        jMemuBar.add(jMenuSistema);

        setJMenuBar(jMemuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAcercaDeActionPerformed
        (new AcercaDe(null, true)).setVisible(true);
    }//GEN-LAST:event_jMenuAcercaDeActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "¿Seguro desea Salir?"  ,"Salir de Sistema",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            System.exit(0);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlumnoActionPerformed
        (new ABMAlumnos(this, true)).setVisible(true);
    }//GEN-LAST:event_jMenuAlumnoActionPerformed

    private void jMenuProfesroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfesroActionPerformed
        (new ABMProfesores(this, true)).setVisible(true);
        
    }//GEN-LAST:event_jMenuProfesroActionPerformed

    private void jMenuCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarreraActionPerformed
       (new CarreraDialog(null,true)).setVisible(true);
    }//GEN-LAST:event_jMenuCarreraActionPerformed

    private void jMenuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMateriaActionPerformed
        (new MateriaDialog(null, true)).setVisible(true);
    }//GEN-LAST:event_jMenuMateriaActionPerformed

    private void jMenuCarreraMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarreraMateriasActionPerformed
        (new CarreraMateriaDialog(null, true)).setVisible(true);
    }//GEN-LAST:event_jMenuCarreraMateriasActionPerformed

    private void jMenuCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCursoActionPerformed
        (new ABMCurso(null, true,false)).setVisible(true);
    }//GEN-LAST:event_jMenuCursoActionPerformed

    private void jMenuAlumnoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlumnoCursoActionPerformed
        CursoAlumnos cursoAlumnos = new CursoAlumnos(this, true);
        cursoAlumnos.setVisible(true);
    }//GEN-LAST:event_jMenuAlumnoCursoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ABMClases abmClases = new ABMClases(this, true);
        abmClases.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuEncriptadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEncriptadorActionPerformed
        // TODO add your handling code here:
        Encriptador encriptador = new Encriptador(this, true);
        encriptador.setLocationRelativeTo(null); 
        encriptador.setVisible(true);
    }//GEN-LAST:event_jMenuEncriptadorActionPerformed

    private void jMenuCursoDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCursoDiasActionPerformed
        // TODO add your handling code here:
        ABMCursoDia abmCursoDia = new ABMCursoDia(this, true);
        abmCursoDia.setVisible(true);
    }//GEN-LAST:event_jMenuCursoDiasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
//        AsistenciaClaseDialog asistenciaClaseDialog = new AsistenciaClaseDialog(this, true);
//        asistenciaClaseDialog.setVisible(true);
        (new ABMCurso(null, true, true)).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsistenciaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsistenciaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsistenciaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsistenciaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsistenciaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMemuBar;
    private javax.swing.JMenu jMenuABM;
    private javax.swing.JMenuItem jMenuAcercaDe;
    private javax.swing.JMenuItem jMenuAlumno;
    private javax.swing.JMenuItem jMenuAlumnoCurso;
    private javax.swing.JMenu jMenuAsistencia;
    private javax.swing.JMenuItem jMenuCarrera;
    private javax.swing.JMenuItem jMenuCarreraMaterias;
    private javax.swing.JMenuItem jMenuCurso;
    private javax.swing.JMenuItem jMenuCursoDias;
    private javax.swing.JMenuItem jMenuEncriptador;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuMateria;
    private javax.swing.JMenuItem jMenuProfesro;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenu jMenuSistema;
    // End of variables declaration//GEN-END:variables
    

}
